/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * editWhichEntry.java
 *
 * Created on Feb 9, 2013, 4:36:32 PM
 */

package dnimas;

/**
 * Class Description - This class gets the index of a student entry to be modified and then creats an instance of the
 * studySessionDescription class to change it.
 *
 * Arguments of the constructor -
 * String[] descriptions2 - array of descriptions submitted by each group member
 *
 * String[] names2 - array of the usernames of the group members
 *
 * String[] passwords2 - array of the passwords of the group members
 *
 * int beginHourNum2, beginMinNum2, endHourNum2, endMinNum2 - beginning and ending hour and minute of group submission
 *
 * descriptionConfirmation dc2 - Instance of the descriptionConfirmation class currently displayed. Used to destroy the current instance when information
 *                               needs to be updated
 *
 * String[] fileName - array of filenames for the work which has been uploaded by the group
 *
 * Class Attributes: Most attributes are set by arguments from the constructor. The attributes that are set from arguments of the constructor can be defined by the values that are used to set them.
 * So refer to the description of the constructor inputs to understand the how the attribute is used.
 *
 * String[] names - namesS2
 * String[] passwords - passwordsS2
 * String[] descriptions - descriptionsS2
 * String[] file - fileName
 * int beginHourNum - beginHoutNum2
 * int beginMinNum - beginMinNum2
 * int endHourNum - endHourNum2
 * int endMinNum - endMinNum2
 * descriptionConfirmation dc1 - dc2
 * int studentEdit - the index of the student to be deleted
 * int range - the number of students in the group
 *
 * Class Methods:
 * submitActionPerformed - Action listener for the submit button
 *    Inputs - the ActionEvent
 */
public class deleteWhichEntry extends javax.swing.JFrame {
    int studentEdit;
    int range;
    String[] file;
    String[] names;
    String[] descriptions;
    String[] passwords;
    int beginHourNum;
    int beginMinNum;
    int endHourNum;
    int endMinNum;
    descriptionConfirmation dc1;
    /** Creates new form editWhichEntry */
    public deleteWhichEntry(String[] descriptions2,String[] names2,String[] passwords2,int beginHourNum2, int beginMinNum2,int endHourNum2, int endMinNum2,descriptionConfirmation dc2,String[] fileName) {
        super("Which Entry?");
        initComponents();
        //set class attributes
        file = fileName;
	dc1 = dc2;
	beginHourNum = beginHourNum2;
	beginMinNum = beginMinNum2;
	endHourNum = endHourNum2;
	endMinNum = endMinNum2;
	descriptions = new String[names2.length];
	names = new String[names2.length];
	passwords = new String[names2.length];
        //Generate list of indices for the students in the group
        String[] studentNums = new String[names2.length];
        Integer holder;
	for(int i=0;i<names2.length;i++){
	   descriptions[i] = descriptions2[i];
	   names[i] = names2[i];
	   passwords[i] = passwords2[i];
           holder = i+1;
           studentNums[i] = holder.toString(); 
	}
        studentSelection.setModel(new javax.swing.DefaultComboBoxModel(studentNums));
        range = names2.length;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        studentSelection = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter the number of the student entry to be deleted");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        studentSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Action listener for the submit button
    //Get the index of the selected student and remove that students information from the passwords, descriptions, and names arrays
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

       int x = Integer.parseInt((String) studentSelection.getSelectedItem())-1;
       int f = 0;
       String[] newDesc = new String[range-1];
       String[] newName = new String[range-1];
       String[] passWor = new String[range-1];

       for(int i=0;i<range-1;i++){
	  if(f==x)
	     f =f+1;
	  newDesc[i] = descriptions[f];
	  newName[i] = names[f];
	  passWor[i] = passwords[f];
	  f=f+1;
       }
       descriptionConfirmation dc = new descriptionConfirmation(newName,newDesc,passWor,beginHourNum,beginMinNum,endHourNum,endMinNum,file);
       dc.setVisible(true);
       dc1.dispose();
       dispose();
    }//GEN-LAST:event_submitActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox studentSelection;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
