/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * groupTime.java
 *
 * Created on Feb 9, 2013, 5:59:00 PM
 */

package dnimas;
import javax.swing.*;

/**
 *
 * @author b.mcclanahan
 */
public class groupTime extends javax.swing.JFrame {
    String[] pass;
    String[] descrip;
    String[] names;
    String file;
    int beginHourNum;
    int beginMinNum;
    int endHourNum;
    int endMinNum;
    descriptionConfirmation dc;
    /** Creates new form groupTime */
    public groupTime(String[] descriptions2,String[] names2,String[] passwords2,descriptionConfirmation dc2,String fileName) {
        super("Time of Session");
        initComponents();
        file = fileName;
	   dc = dc2;
	   names = new String[names2.length];
	   descrip = new String[descriptions2.length];
	   pass = new String[passwords2.length];
	   for(int i=0;i<names2.length;i++)
	   {
		   names[i] = names2[i];
		   descrip[i] = descriptions2[i];
		   pass[i] = passwords2[i];
	   }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        beginHour = new javax.swing.JTextField();
        beginMins = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        endHour = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endMins = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter the time of the session");

        jLabel2.setText(":");

        beginHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginHourActionPerformed(evt);
            }
        });

        jLabel3.setText("pm");

        jLabel4.setText(":");

        jLabel5.setText("pm");

        jLabel6.setText("To:");

        jLabel7.setText("From:");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("*Only times between 6:00pm and 8:00pm are valid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(beginHour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(beginMins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(endHour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endMins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(beginMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(endMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beginHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginHourActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
		   try{
			   beginHourNum = Integer.parseInt(beginHour.getText());
			   beginMinNum = Integer.parseInt(beginMins.getText());
			   endHourNum = Integer.parseInt(endHour.getText());
			   endMinNum = Integer.parseInt(endMins.getText());
                           if(beginHourNum <=8 && beginHourNum>=6 && endHourNum<=8 && endHourNum>=6)
                           {
			      if(beginHourNum>endHourNum)
		                 JOptionPane.showMessageDialog(null, "Your input is invalid");
			      else if(beginHourNum == endHourNum && beginMinNum>endMinNum)
				   JOptionPane.showMessageDialog(null, "Your input is invalid");
		   	      else if(endHourNum<1 || beginHourNum <1)
				   JOptionPane.showMessageDialog(null, "Your input is invalid");
			      else if(endHourNum>12 || beginHourNum>12)
				   JOptionPane.showMessageDialog(null, "Your input is invalid");
			      else if(endMinNum<0 ||beginMinNum<0)
				   JOptionPane.showMessageDialog(null, "Your input is invalid");
			      else if(endMinNum>59||beginMinNum>59)
				   JOptionPane.showMessageDialog(null, "Your input is invalid");
			      else
			      {
				   descriptionConfirmation dc1 = new descriptionConfirmation(names,descrip,pass,beginHourNum,beginMinNum,endHourNum,endMinNum,file);
				   dc1.setVisible(true);
				   dc.dispose();
				   dispose();
			      }
                           }
                           else
                              JOptionPane.showMessageDialog(null, "Your input is invalid");
		   }catch(Exception ex){
			   JOptionPane.showMessageDialog(null, "Your input is invalid");
		   }
    }//GEN-LAST:event_submitActionPerformed

    /**
    * @param args the command line arguments
    */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beginHour;
    private javax.swing.JTextField beginMins;
    private javax.swing.JTextField endHour;
    private javax.swing.JTextField endMins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
